pr_title: 'chore: sync with ecsact_common'
files_dir: files
author_login: seaubot
repos:
  - ecsact_runtime
  - ecsact_parse
  - ecsact_interpret
  - ecsact_codegen
  - ecsact_cli
  - ecsact_si_wasm
  - ecsact_lang_json
  - ecsact_lang_cpp
  - ecsact_lang_csharp
  - ecsact_lsp_server
  - ecsact_rt_entt
  - ecsact_rt_reference
