# This file is maintained by ecsact-dev/ecsact_common
# If changes are required please make them there

name: main

on:
  pull_request:
  merge_group:

jobs:
  typos-check:
    name: Typos Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@685eb3d55be2f85191e8c84acb9f44d7756f84ab # v1.29.4

  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: greut/eclint-action@v0
      - uses: jidicula/clang-format-action@v4.11.0
        with: { clang-format-version: "19" }

  test-windows:
    if: >-
      (github.event_name == 'pull_request' && (github.event.pull_request.user.login == 'renovate[bot]' || github.event.pull_request.user.login == 'seaubot'))
      || (github.event_name == 'merge_group' && github.event.pull_request.user.login != 'renovate[bot]' && github.event.pull_request.user.login != 'seaubot')
      || contains(github.event.pull_request.labels.*.name, 'ci:always')
    runs-on: windows-latest
    steps:
      - uses: actions/cache@v4
        with:
          path: |
            /Users/runneradmin/AppData/Local/bazelisk
            /Users/runneradmin/.cache/bazel-disk-cache
          key: ${{runner.os}}-bazel-cache
      - uses: actions/checkout@v4
      - run: bazelisk build --config=ci //...
      - if: ${{ hashfiles('test/MODULE.bazel') != '' }}
        run: bazelisk test --config=ci ...
        working-directory: test

  test-linux:
    if: >-
      (github.event_name == 'pull_request' && (github.event.pull_request.user.login == 'renovate[bot]' || github.event.pull_request.user.login == 'seaubot'))
      || (github.event_name == 'merge_group' && github.event.pull_request.user.login != 'renovate[bot]' && github.event.pull_request.user.login != 'seaubot')
      || contains(github.event.pull_request.labels.*.name, 'ci:always')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel-disk-cache
          key: ${{runner.os}}-bazel-cache
      - uses: actions/checkout@v4
      - run: bazelisk build --config=ci //...
      - if: ${{ hashfiles('test/MODULE.bazel') != '' }}
        run: bazelisk test --config=ci ...
        working-directory: test
