name: Sync common files
on:
  push:
      branches: [ main ]
jobs:
  sync_common_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: derberg/manage-files-in-multiple-repositories@v2.1.0
        with:
          github_token: ${{ secrets.SEAUBOT_ECSACT_DEV_GH_TOKEN }}
          patterns_to_ignore: '.github/workflows/sync-files.yml'
          exclude_private: true
          exclude_forked: true
          branches: main
          committer_username: seaubot
          committer_email: seaubot@users.noreply.github.com
          commit_message: "chore: sync with ecsact_common"
