name: Sync common files
on:
  push: {branches: [main]}
  workflow_dispatch: {}

jobs:
  sync_common_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
      - run: go run main.go
        env:
          GH_TOKEN: ${{ secrets.SEAUBOT_ECSACT_DEV_GH_TOKEN }}
