name: Sync common files
on:
  push: {branches: [main]}
  workflow_dispatch: {}

jobs:
  sync_common_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: go run main.go
        env:
          GH_TOKEN: ${{ secrets.SEAUBOT_ECSACT_DEV_GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.SEAUBOT_ECSACT_DEV_GH_TOKEN }}
